site_name: Seafile Admin Manual
site_author: seafile
docs_dir: ./manual
site_url: https://haiwen.github.io/seafile-admin-docs/

repo_name: haiwen/seafile-admin-docs
repo_url: https://github.com/haiwen/seafile-admin-docs/
edit_uri: blob/master/manual

copyright: Copyright &copy; 2024 Seafile Ltd.

theme:
  name: material
  logo: media/seafile-transparent-1024.png
  favicon: media/favicon.ico
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - mike

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiwen/seafile-admin-docs/
  version:
    provider: mike
  status:
    new: Work in progress

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"

# Page tree
nav:
  - Introduction:
    - Introduction: introduction/README.md
    - Seafile Components: introduction/components.md
    - File permission management: introduction/file_permission_management.md
    - Roadmap: introduction/roadmap.md
    - Contribution: introduction/contribution.md
  - Setup:
    - Overview: setup/overview.md
    - Single node installation:
      - Setup community edition: setup/single_node_installation/setup_community_edition.md
      - Setup pro edition: setup/single_node_installation/setup_pro_edition.md
    - Advanced topics:
      - Storage Backends:
        - S3 Backend: setup/advanced_topics/storage_backends/setup_with_amazon_s3.md
        - Ceph Backend: setup/advanced_topics/storage_backends/setup_with_ceph.md
        - OpenStack Swift Backend: setup/advanced_topics/storage_backends/setup_with_swift.md
        - Alibaba OSS: setup/advanced_topics/storage_backends/setup_with_oss.md
        - Multiple Storage Backends: setup/advanced_topics/storage_backends/multiple_storage_backends.md
        - Data migration: setup/advanced_topics/storage_backends/migrate.md
      - Seafile Docker autostart: setup/advanced_topics/seafile_docker_autostart.md
      - Deploy with an existing MySQL server: setup/advanced_topics/deploy_seafile_with_an_existing_mysql_server.md
      - Run Seafile as non root user inside docker: setup/advanced_topics/run_seafile_as_non_root_user_inside_docker.md
    - Cluster installation:
      - Seafile Docker Cluster Deployment: setup/cluster_installation/deploy_seafile_cluster_with_docker.md
      - Setup with Kubernetes (K8s): setup/cluster_installation/deploy_with_k8s.md
    - Migration:
      - Migration from Seafile Community: setup/migration/migrate_ce_to_pro_with_docker.md
      - Migrate from non-docker deployment: setup/migration/non_docker_to_docker.md
  - Setup (binary):
    - Seafile Community Setup:
      - Outline: setup_binary/ce/README.md
      - Installation: setup_binary/ce/installation.md
      - HTTPS with Nginx: setup_binary/ce/https_with_nginx.md
      - HTTPS with Apache: setup_binary/ce/https_with_apache.md
    - Seafile Professional Setup:
      - Outline: setup_binary/pro/README.md
      - Installation: setup_binary/pro/installation.md
      - Migration from Seafile Community: setup_binary/pro/migrate_from_seafile_community_server.md
      - Cluster deployment:
        - Deploy in a cluster: setup_binary/pro/cluster/deploy_in_a_cluster.md
        - Search and background tasks in a cluster: setup_binary/pro/cluster/enable_search_and_background_tasks_in_a_cluster.md
        - Memcache and MariaDB Cluster: setup_binary/pro/cluster/memcached_mariadb_cluster.md
        - Setup Seafile cluster with NFS: setup_binary/pro/cluster/setup_seafile_cluster_with_nfs.md
      - License: setup_binary/pro/seafile_professional_sdition_software_license_agreement.md
    - Other deployment notes:
      - Start Seafile at System Bootup: setup_binary/other_deployment_notes/start_seafile_at_system_bootup.md
      - Logrotate: setup_binary/other_deployment_notes/using_logrotate.md
      - Config fail2ban: setup_binary/other_deployment_notes/fail2ban.md
      - Migrate From SQLite to MySQL: setup_binary/other_deployment_notes/migrate_from_sqlite_to_mysql.md
  - Extensions:
    - Extra Seafile components:
      - SeaDoc Integration: extension/extra_components/setup_seadoc.md
      - Notification Server: extension/extra_components/notification-server.md
      - WebDAV extension: extension/extra_components/webdav.md
      - FUSE extension: extension/extra_components/fuse.md
    - Online Office:
      - LibreOffice Online Integration: extension/online_office/libreoffice_online.md
      - OnlyOffice Integration: extension/online_office/only_office.md
      - Office Online Server Integration (Pro): extension/online_office/office_web_app.md
    - Virus Scan (Pro):
      - Outline: extension/virus_scan/virus_scan.md
      - Virus scan with ClamAV: extension/virus_scan/deploy_clamav_with_seafile.md
      - Virus scan with Kav4fs: extension/virus_scan/virus_scan_with_kav4fs.md
  - Configuration:
    - Authentication & Users:
      - LDAP/AD Integration:
        - LDAP Integration: config/authentication/ldap/ce/ldap_in_11.0.md
        - LDAP Integration (Pro): config/authentication/ldap/pro/ldap_in_11.0.md
      - Single Sign On:
        - Outline: config/authentication/sso/single_sign_on.md
        - OAuth Authentication: config/authentication/sso/oauth.md
        - Remote User Authentication: config/authentication/sso/remote_user.md
        - Shibboleth Authentication: config/authentication/sso/shibboleth_authentication.md
        - Auto Login to SeaDrive on Windows: config/authentication/sso/auto_login_seadrive.md
        - SAML 2.0 (Pro): config/authentication/sso/saml2_in_10.0.md
        - Switch authentication: config/authentication/sso/auth_switch.md
      - Advanced User Management (Pro):
        - Multi-Institutions Support: config/authentication/advanced_user_management/multi_institutions.md
        - Roles and Permissions: config/authentication/advanced_user_management/roles_permissions.md
        - Administrator Roles and Permissions: config/authentication/advanced_user_management/admin_roles_permissions.md
        - Multi-Tenancy Support: config/authentication/advanced_user_management/multi_tenancy.md
    - Advanced File Search configuration (Pro): config/authentication/details_about_file_search.md
    - Open Cloud Mesh: config/authentication/ocm.md
    - Available configuration options:
      - Outline: config/seafile_config/README.md
      - Environment variables: config/seafile_config/env.md
      - ccnet.conf: config/seafile_config/ccnet-conf.md
      - seafile.conf: config/seafile_config/seafile-conf.md
      - seahub_settings.py: config/seafile_config/seahub_settings_py.md
      - seafevents.conf: config/seafile_config/seafevents-conf.md
      - Seahub customization: config/seafile_config/seahub_customization.md
      - Email Sending: config/seafile_config/sending_email.md
  - Administration:
    - Outline: administration/README.md
    - Account management: administration/account.md
    - Two-factor Authentication: administration/two_factor_authentication.md
    - Security features: administration/security_features.md
    - Access logs and auditing: administration/auditing.md
    - Export report: administration/export_report.md
    - Logs: administration/logs.md
    - Backup and Recovery: administration/backup_recovery.md
    - Seafile FSCK: administration/seafile_fsck.md
    - Seafile GC: administration/seafile_gc.md
    - Clean database: administration/clean_database.md
  - Upgrade:
    - Outline: upgrade/upgrade.md
    - Upgrade Seafile Docker: upgrade/upgrade_docker.md
    - Upgrade Seafile Cluster: upgrade/upgrade_a_cluster.md
    - Upgrade Seafile Cluster (Docker): upgrade/upgrade_a_cluster_docker.md
    - Upgrade notes for 7.0.x: upgrade/upgrade_notes_for_7.0.x.md
    - Upgrade notes for 7.1.x: upgrade/upgrade_notes_for_7.1.x.md
    - Upgrade notes for 8.0.x: upgrade/upgrade_notes_for_8.0.x.md
    - Upgrade notes for 9.0.x: upgrade/upgrade_notes_for_9.0.x.md
    - Upgrade notes for 10.0.x: upgrade/upgrade_notes_for_10.0.x.md
    - Upgrade notes for 11.0.x: upgrade/upgrade_notes_for_11.0.x.md
    - Upgrade notes for 12.0.x: upgrade/upgrade_notes_for_12.0.x.md
  - Developing:
    - Outline: develop/README.md
    - How to Build Seafile:
      - Outline: develop/build_seafile/README.md
      - Linux: develop/build_seafile/linux.md
      - macOS: develop/build_seafile/osx.md
      - Windows: develop/build_seafile/windows.md
      - Server development: develop/build_seafile/server.md
      - Server binary package: develop/build_seafile/rpi.md
    - Translation: develop/translation.md
    - Web API V2.1: develop/web_api_v2.1.md
    - PHP API: https://github.com/rene-s/Seafile-PHP-SDK
    - Data Model: develop/data_model.md
  - ChangeLog:
    - Seafile Community Edition: changelog/server-changelog.md
    - Seafile Professional Edition: changelog/changelog-for-seafile-professional-server.md
    - Seafile Client: changelog/client-changelog.md
    - Drive Client: changelog/drive-client-changelog.md
